
CREATE DATABASE car_shop;
USE car_shop;

/* TO READ ALL DATA*/
SELECT * FROM car;

/* TOTAL CARS: TOTAL COUNT OF DATA*/
SELECT COUNT(*) FROM car;

/* TOTAL DISTINCT COUNT OF CARS*/
SELECT COUNT(DISTINCT(Name)) AS total_cars FROM car;

/*YEARS IN THE DATA*/
SELECT DISTINCT(year) AS total_year FROM car;

/*TOTAL COUNT OF YEARS IN DATA*/
SELECT count((year)) AS total_year FROM car;

/*WICH CARS WILL BE AVAILABLE IN 2023*/
SELECT Name, year FROM car WHERE year=2023;

/*COUNT OF CARS AVAILABLE IN 2023*/
SELECT COUNT(Name) AS total_cars, year FROM car WHERE year=2023;

/*HOW MANY CARS WILL BE AVAILABLE IN 2020,2021,2022*/
SELECT COUNT(Name), year FROM car WHERE year IN(2020,2021,2022) GROUP BY year;

/*TOTAL OF ALL CARS BY YEAR*/
SELECT COUNT(Name),year FROM car GROUP BY year ORDER BY year DESC;

/*HOW MANY DIESEL CARS ARE THERE IN DATA IN 2020*/
SELECT COUNT(Name) AS cars,year,fuel FROM car WHERE year=2020 AND fuel="Diesel" ;

/*HOW MANY PETROL CARS ARE THERE IN DATA IN 2017*/
SELECT COUNT(Name) AS cars,year,fuel FROM car WHERE year=2017 AND fuel="Petrol" ;

/*WHICH YEAR HAD MORE THAN 100 CARS*/
SELECT COUNT(Name) AS total_cars, year FROM car GROUP BY year HAVING total_cars>100;

/* ALL THE CARS OF CNG COME BY ALL THE YEARS*/
SELECT COUNT(Name), year, fuel FROM car WHERE fuel="CNG" GROUP BY year;

/*WHICH YEAR HAD LESS THAN 50 PETROL CARS*/
SELECT COUNT(Name) AS total_cars, year, fuel FROM car WHERE fuel="Petrol" GROUP BY year HAVING total_cars<50;

/*COUNT OF CARS BETWEEN 2015 TO 2023*/
SELECT COUNT(*) FROM car WHERE year BETWEEN 2015 AND 2023;

/* ALL DETAILS OF DIESEL CARS BETWEEN YEAR 2017 TO 2022*/
SELECT * FROM car WHERE fuel="Diesel" AND year BETWEEN 2015 AND 2023;

/* ALL PETROL CARS HAVING PRICE GREATER THAN 80,000*/
SELECT Name,fuel,selling_price FROM car WHERE fuel="Petrol" HAVING selling_price>80000;

/*ALL DETAILS OF CNG CARS WHICH IS OWNED BY FIRST OWNER*/
SELECT * FROM car WHERE owner="First Owner" AND fuel="CNG";

/*ALL PETROL CARS OWNED BY FIRST OWNER HAVING ENGINE MORE THAN 700 CC*/
SELECT Name,fuel,owner,engine FROM car WHERE owner="First Owner" AND fuel="Petrol" HAVING engine>700;

/*ALL CARS IN YEAR 2020,2021,2022,2023 WHOSE SELLER TYPE IS INDIVIDUAL AND HAVING ENGINE MORE THAN 1000*/
SELECT Name,year,seller_type,engine FROM car WHERE YEAR IN(2020,2021,2022,2023) AND seller_type="Individual" HAVING engine>700;

/*MOST EXPENSIVE CAR IN SHOP*/
SELECT Name,selling_price FROM car ORDER BY selling_price DESC LIMIT 1;

/*MOST EXPENSIVE CAR WHICH IS DRIVEN UPTO 1000 KM*/
SELECT Name,selling_price,km_driven FROM car WHERE km_driven=1000 ORDER BY selling_price DESC LIMIT 1;

/*ALL DETAILS OF CAR WHO HAS MILEAGE BETWEEN 12 TO 19 AND ENGINE MORE THAN 900CC AND HAVING 5 SEATS*/
SELECT * FROM car WHERE seats=5 AND mileage BETWEEN 12.00 AND 19.00 HAVING engine>900;

/* FIND CAR NAME AND PRICE OF CHEAPEST CAR*/
SELECT Name, selling_price FROM car ORDER BY selling_price ASC LIMIT 1;

/* FIND ALL DETAILS OF CARS HAVING MAX_POWER ATLEAST 70BHP WITH SELLER_TYPE INDIVIDUAL*/
SELECT * FROM car WHERE seller_type="Individual" HAVING max_power>70;

/*FIND AVG KM DRIVEN OF ALL TYPE OF FUEL CARS HAVING SELLING PRICE MORE THAN 50000 AND WHICH IS OWNED BY FIRST OWNER*/
SELECT COUNT(Name), fuel, ROUND(AVG(km_driven)), owner FROM car WHERE owner="First Owner" AND selling_price>50000 GROUP BY fuel ;

/*FIND AVG PRICE OF ALL CARS ACCORDING TO YEARS*/
SELECT COUNT(Name),ROUND(AVG(selling_price)), year FROM car GROUP BY year;

/* ALL CNG CARS BETWEEN PRICE 50000 TO 700000 having 5 Seats*/
SELECT * FROM car WHERE seats=5 AND selling_price BETWEEN 50000 AND 700000;

/*HOW MANY CNG CARS ARE THERE IN ALL YEARS HAVING TRANSMISSION MANUAL*/
SELECT COUNT(Name),fuel,year,transmission FROM car WHERE fuel="CNG" AND transmission="Manual" GROUP BY YEAR;

/*AVG PRICE OF ALL CARS ACCORDING TO YEAR WITH AVG KM DRIVEN WITH TRANSMISSION MANUAL*/
SELECT COUNT(Name),AVG(selling_price),year,AVG(km_driven),transmission FROM car WHERE transmission="Manual" GROUP BY year;

/*ALL DETAILS OF PETROL CARS HAVING KM DRIVEN MORE THAN 1000 AND HAVING SEATS MORE THAN 2*/
SELECT * FROM car WHERE fuel="Petrol" AND km_driven>1000 AND seats>2;

/*RECOGNISING CARS CATEGORY ACCORDING TO PRICE*/
SELECT Name,selling_price,
CASE
WHEN selling_price>150000 THEN "VERY COSTLY"
WHEN selling_price>100000 AND selling_price<150000 THEN "COSTLY" 
WHEN selling_price>50000 AND selling_price<100000 THEN "CHEAP"
WHEN selling_price>10000 AND selling_price<50000 THEN "VERY CHEAP" 
ELSE "NO DATA"
END AS verdict
FROM car;

/*FIND THE CAR WHO HAS TOP 5 MILEAGE IN YEAR 2023*/
SELECT Name,year,mileage FROM car WHERE year=2023 ORDER BY mileage DESC LIMIT 5;

/* FIND NAME AND PRICE OF DIESEL CARS WHO HAS ENGINE BETWEEN 900 TO 2000*/
SELECT Name, selling_price,fuel,engine FROM car WHERE fuel="Diesel" AND engine BETWEEN 900 AND 2000;

/*COUNT OF CNG CARS ACCORDING TO YEAR*/
SELECT COUNT(Name),year,fuel FROM car WHERE fuel="CNG" GROUP BY year;

/*costly electric car*/
SELECT Name,fuel,selling_price FROM car WHERE fuel="Electric" ORDER BY selling_price;

/* PRICE OF PETROL CAR HAVING TOP 5 MAXIMUM TORQUE*/
SELECT Name,selling_price,fueL,torque FROM car WHERE fuel="Petrol" ORDER BY torque DESC LIMIT 5;

/*TOP 5 CHEAPEST CAR IN YEAR 2020*/
SELECT Name,year,selling_price FROM car WHERE year=2020 ORDER BY selling_price ASC LIMIT 5;

/*HOW MANY KM DRIVEN DOES THE CHEAPEST CAR HAVE*/
SELECT Name,selling_price,km_driven FROM car ORDER BY selling_price LIMIT 1;

/* costest car having 7 seats*/
select Name,selling_price,seats FROM car WHERE seats=7 ORDER BY selling_price LIMIT 1;